[package]
name = "tibuilder"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.15"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tibrs = "0.1.3"
