// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "auth:get_oauth2_url", input: never, result: GetOauth2UrlParams } | 
        { key: "program:compile", input: CompileProgramParams, result: CompileProgramResp } | 
        { key: "program:get", input: GetProgramParams, result: Program } | 
        { key: "program:list", input: never, result: Program[] },
    mutations: 
        { key: "program:create", input: CreateProgramParams, result: Program } | 
        { key: "program:delete", input: number, result: null } | 
        { key: "program:update", input: UpdateProgramParams, result: Program },
    subscriptions: never
};

export type GetOauth2UrlParams = { url: string }

export type Program = { id: number; userId: string; name: string; createdAt: string; blockly: string | null; public: boolean }

export type CompileProgramResp = { status: "Ok"; buffer: number[] } | { status: "Err"; reason: string }

export type GetProgramParams = { program_id: number }

export type CompileProgramParams = { program_id: number }

export type CreateProgramParams = { name: string; blockly: string }

export type UpdateProgramParams = { id: number; name: string; blockly: string; public: boolean }
